version: '3'

services:
  github-search:
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./output:/app/output
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    